[package]
name = "store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
actix-web = "3"
actix-cors = "0.5.4"
diesel = { version = "1.4.7", features = ["postgres", "chrono", "uuid"] }
dotenv = "0.15.0"